name: Continuous Integration
on: [push]

jobs:
    linter:
        name: Code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
            - run: 'composer update --prefer-dist --no-interaction'
            - run: vendor/bin/php-cs-fixer fix -v --dry-run

    stan:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
            - run: 'composer update --prefer-dist --no-interaction'
            - run: vendor/bin/phpstan analyse src

    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['8.0', '8.1', '8.2']
                flags: ['--prefer-lowest', '--prefer-stable']
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.version }}
            - run: 'composer update --prefer-dist --no-interaction ${{ matrix.flags }}'
            - run: 'vendor/bin/phpunit'
